jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      go get -tags "sqlite integration_test" -u -t -v ./...
      go test -tags "sqlite integration_test" -v ./...
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      go get -tags "sqlite integration_test" -u -t -v ./...
      go test -tags "sqlite integration_test" -v ./...
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      go get -tags "sqlite integration_test" -u -t -v ./...
      go test -tags "sqlite integration_test" -v ./...
